//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDigital {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestDigital.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información ingresada:.
        /// </summary>
        internal static string DetailHeading {
            get {
                return ResourceManager.GetString("DetailHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string DetailTitle {
            get {
                return ResourceManager.GetString("DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección: {0}.
        /// </summary>
        internal static string DetailUserAddress {
            get {
                return ResourceManager.GetString("DetailUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio: {0}.
        /// </summary>
        internal static string DetailUserCity {
            get {
                return ResourceManager.GetString("DetailUserCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento: {0}.
        /// </summary>
        internal static string DetailUserDepto {
            get {
                return ResourceManager.GetString("DetailUserDepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario: {0}.
        /// </summary>
        internal static string DetailUserName {
            get {
                return ResourceManager.GetString("DetailUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu dirección: (Calle/Numero/Apto).
        /// </summary>
        internal static string HomeAddressHint {
            get {
                return ResourceManager.GetString("HomeAddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu dirección:.
        /// </summary>
        internal static string HomeAddressLbl {
            get {
                return ResourceManager.GetString("HomeAddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        internal static string HomeCityLbl {
            get {
                return ResourceManager.GetString("HomeCityLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string HomeConfirmBtn {
            get {
                return ResourceManager.GetString("HomeConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor confirma tu información:.
        /// </summary>
        internal static string HomeConfirmLbl {
            get {
                return ResourceManager.GetString("HomeConfirmLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        internal static string HomeDeptLbl {
            get {
                return ResourceManager.GetString("HomeDeptLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Municipio.
        /// </summary>
        internal static string HomeSelectCity {
            get {
                return ResourceManager.GetString("HomeSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Departamento.
        /// </summary>
        internal static string HomeSelectDepto {
            get {
                return ResourceManager.GetString("HomeSelectDepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted es el usuario {0} .
        /// </summary>
        internal static string HomeUsrWelcomeLbl {
            get {
                return ResourceManager.GetString("HomeUsrWelcomeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario llenar los campos..
        /// </summary>
        internal static string LoginEmptyInfo {
            get {
                return ResourceManager.GetString("LoginEmptyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPasswordEntryHint {
            get {
                return ResourceManager.GetString("LoginPasswordEntryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string LoginUserEntryHint {
            get {
                return ResourceManager.GetString("LoginUserEntryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o password incorrecto.
        /// </summary>
        internal static string LoginWrongInfoAlert {
            get {
                return ResourceManager.GetString("LoginWrongInfoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta!!!.
        /// </summary>
        internal static string UtilsAlert {
            get {
                return ResourceManager.GetString("UtilsAlert", resourceCulture);
            }
        }
    }
}
